# Generated by Django 4.2.1 on 2023-05-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0005_remove_affiliation_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliation",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
