# Generated by Django 4.2.1 on 2023-05-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0006_affiliation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
