# Generated by Django 4.2.1 on 2023-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0007_alter_affiliation_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliation",
            name="name",
        ),
        migrations.AddField(
            model_name="affiliation",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
