# Generated by Django 4.2.1 on 2023-05-16 11:25

import appointmentio.utils
import autoslug.fields
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=appointmentio.utils.get_appointment_slug, unique=True)),
                ('appointment_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOWUP', 'FollowUp'), ('OTHER', 'Other')], default='CONSULTATION', max_length=20)),
                ('appointment_for', models.CharField(choices=[('MYSELF', 'Myself'), ('OTHER', 'Other')], default='MYSELF', max_length=20)),
                ('complication', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], default='REQUESTED', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='use for visibility.')),
                ('conference_link', models.URLField(blank=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('schedule_start', models.DateTimeField(blank=True, help_text='Start Time', verbose_name='Appointment schedule start time.')),
                ('schedule_end', models.DateTimeField(blank=True, help_text='End Time', null=True, verbose_name='Appointment schedule start time.')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('serial_number', models.PositiveIntegerField(db_index=True, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=appointmentio.utils.get_appointment_slug)),
                ('appointment_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOWUP', 'FollowUp'), ('OTHER', 'Other')], default='CONSULTATION', max_length=20)),
                ('appointment_for', models.CharField(choices=[('MYSELF', 'Myself'), ('OTHER', 'Other')], default='MYSELF', max_length=20)),
                ('complication', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], default='REQUESTED', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='use for visibility.')),
                ('conference_link', models.URLField(blank=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('schedule_start', models.DateTimeField(blank=True, help_text='Start Time', verbose_name='Appointment schedule start time.')),
                ('schedule_end', models.DateTimeField(blank=True, help_text='End Time', null=True, verbose_name='Appointment schedule start time.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical appointment',
                'verbose_name_plural': 'historical appointments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('side_effects', models.TextField(blank=True)),
                ('package_size', models.CharField(blank=True, max_length=255)),
                ('package_type', models.CharField(blank=True, max_length=255)),
                ('storage_conditions', models.CharField(blank=True, max_length=255)),
                ('expiration_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed'), ('RESTRICTED', 'Restricted'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=30)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_visit', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=30)),
                ('type', models.CharField(choices=[('ADVICES', 'Advices'), ('DIAGNOSIS', 'Diagnosis'), ('COMPLAINTS', 'Complaints'), ('EXAMINATIONS', 'Examinations')], default='ADVICES', max_length=30)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionMedicineConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, max_length=255)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled')], default='REQUESTED', max_length=30)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmentio.appointment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
