# Generated by Django 4.2.1 on 2023-05-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctorio', '0001_initial'),
        ('accountio', '0002_affiliation_doctor_affiliation_organization_and_more'),
        ('appointmentio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctorio.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='accountio.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='appointmentio.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='patientio.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='doctorio.doctor'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointmentio.appointment'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patientio.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='appointmentio.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='doctorio.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='appointmentio.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='patientio.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptioninformation',
            name='doctor',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='doctorio.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptioninformation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='appointmentio.prescriptioninformation'),
        ),
        migrations.AddField(
            model_name='prescriptioninformation',
            name='prescription',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='appointmentio.prescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionmedicineconnector',
            name='medicine',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='appointmentio.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionmedicineconnector',
            name='prescription',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='appointmentio.prescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refill',
            name='patient',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='patientio.patient'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionmedicineconnector',
            unique_together={('prescription', 'medicine')},
        ),
        migrations.AlterUniqueTogether(
            name='refill',
            unique_together={('patient', 'appointment')},
        ),
    ]
