# Generated by Django 4.2.1 on 2023-05-19 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentio', '0003_remove_appointment_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='schedule_requested',
            field=models.DateField(default=django.utils.timezone.now, help_text='Appointment requested date from patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='schedule_requested',
            field=models.DateField(default=django.utils.timezone.now, help_text='Appointment requested date from patient'),
            preserve_default=False,
        ),
    ]
