# Generated by Django 4.2.1 on 2023-05-19 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0004_appointment_schedule_requested_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptioninformation",
            name="treatment",
        ),
    ]
