# Generated by Django 4.2.1 on 2023-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointmentio",
            "0006_appointment_blood_group_appointment_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("FOLLOWUP", "FollowUp"),
                    ("SPECIALIST", "Specialist"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("FOLLOWUP", "FollowUp"),
                    ("SPECIALIST", "Specialist"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
