# Generated by Django 4.2.1 on 2023-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0007_alter_appointment_appointment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="seek_help",
            field=models.CharField(
                choices=[
                    ("CHEST_DISCOMFORT", "Chest Discomfort"),
                    ("PALPITATIONS", "Palpitations"),
                    ("SHORTNESS_OF_BREATH", "Shortness of Breath"),
                    ("SYNCOPE", "Syncope"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalappointment",
            name="seek_help",
            field=models.CharField(
                choices=[
                    ("CHEST_DISCOMFORT", "Chest Discomfort"),
                    ("PALPITATIONS", "Palpitations"),
                    ("SHORTNESS_OF_BREATH", "Shortness of Breath"),
                    ("SYNCOPE", "Syncope"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
