# Generated by Django 4.2.1 on 2023-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentio', '0008_appointment_seek_help_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
