# Generated by Django 4.2.1 on 2023-06-14 05:20

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("patientio", "0004_relativepatient_medicalhistory_relative_patient"),
        ("accountio", "0008_remove_affiliation_name_affiliation_hospital_name"),
        ("appointmentio", "0012_alter_appointment_blood_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeekHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="schedule_requested",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="seek_help",
        ),
        migrations.RemoveField(
            model_name="historicalappointment",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="historicalappointment",
            name="schedule_requested",
        ),
        migrations.RemoveField(
            model_name="historicalappointment",
            name="seek_help",
        ),
        migrations.AddField(
            model_name="appointment",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_visible",
            field=models.BooleanField(default=False, help_text="Use for visibility."),
        ),
        migrations.AddField(
            model_name="appointment",
            name="relative_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patientio.relativepatient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="symptom_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOUR_HOURS", "4 Hours"),
                    ("ONE_TO_THREE_DAYS", "1-3 Days"),
                    ("FOUR_DAYS_TO_A_WEEK", "4 Days to a Week"),
                    ("ONE_WEEK_To_A_MONTH", "1 Week to a Month"),
                    ("ONE_TO_SIX_MONTHS", "1-6 Months"),
                    ("SIX_MONTH_TO_A_YEAR", "6 Months to a Year "),
                    ("MORE_THAN_ONE_YEAR", "More Than One Year"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="historicalappointment",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalappointment",
            name="is_visible",
            field=models.BooleanField(default=False, help_text="Use for visibility."),
        ),
        migrations.AddField(
            model_name="historicalappointment",
            name="relative_patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patientio.relativepatient",
            ),
        ),
        migrations.AddField(
            model_name="historicalappointment",
            name="symptom_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOUR_HOURS", "4 Hours"),
                    ("ONE_TO_THREE_DAYS", "1-3 Days"),
                    ("FOUR_DAYS_TO_A_WEEK", "4 Days to a Week"),
                    ("ONE_WEEK_To_A_MONTH", "1 Week to a Month"),
                    ("ONE_TO_SIX_MONTHS", "1-6 Months"),
                    ("SIX_MONTH_TO_A_YEAR", "6 Months to a Year "),
                    ("MORE_THAN_ONE_YEAR", "More Than One Year"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="is_visible",
            field=models.BooleanField(
                default=False, help_text="Is doctor can read medical records."
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="relative_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patientio.relativepatient",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_for",
            field=models.CharField(
                choices=[("ME", "Me"), ("SOMEONE_ELSE", "Someone Else")],
                default="ME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("CONSULTATION", "Consultation"),
                    ("FOLLOWUP", "Follow Up"),
                    ("OTHER", "Other"),
                ],
                default="FOLLOWUP",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_SET", "Not Set"),
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "Ab Positive"),
                    ("AB-", "Ab Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("UNKNOWN", "Unknown"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("REQUESTED", "Requested"),
                    ("SCHEDULED", "Scheduled"),
                    ("PENDING", "Pending"),
                    ("CANCELED", "Canceled"),
                    ("HIDDEN", "Hidden"),
                    ("REMOVED", "Removed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="appointment_for",
            field=models.CharField(
                choices=[("ME", "Me"), ("SOMEONE_ELSE", "Someone Else")],
                default="ME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("CONSULTATION", "Consultation"),
                    ("FOLLOWUP", "Follow Up"),
                    ("OTHER", "Other"),
                ],
                default="FOLLOWUP",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_SET", "Not Set"),
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "Ab Positive"),
                    ("AB-", "Ab Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("UNKNOWN", "Unknown"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("REQUESTED", "Requested"),
                    ("SCHEDULED", "Scheduled"),
                    ("PENDING", "Pending"),
                    ("CANCELED", "Canceled"),
                    ("HIDDEN", "Hidden"),
                    ("REMOVED", "Removed"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DateTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "time_schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONE", "1:00"),
                            ("TWO", "2:00"),
                            ("THREE", "3:00"),
                            ("FOUR", "4:00"),
                            ("FIVE", "5:00"),
                            ("SIX", "6:00"),
                            ("SEVEN", "7:00"),
                            ("EIGHT", "8:00"),
                            ("NINE", "9:00"),
                            ("TEN", "10:00"),
                            ("ELEVEN", "11:00"),
                            ("TWELVE", "12:00"),
                        ],
                        max_length=20,
                    ),
                ),
                ("slot", models.TimeField(blank=True, null=True)),
                ("is_booked", models.BooleanField(default=False)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountio.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AppointmentSeekHelpConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seek_help_for",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.appointment",
                    ),
                ),
                (
                    "seek_help",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.seekhelp",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AppointmentMedicationConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "other_medicine",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.appointment",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AppointmentAllergicMedicationConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "other_medicine",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.appointment",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
