# Generated by Django 4.2.1 on 2023-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0013_seekhelp_remove_appointment_is_private_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datetimeslot",
            name="time_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5:00", "5:00"),
                    ("6:00", "6:00"),
                    ("7:00", "7:00"),
                    ("8:00", "8:00"),
                ],
                max_length=20,
            ),
        ),
    ]
