# Generated by Django 4.2.1 on 2023-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0014_alter_datetimeslot_time_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="symptom_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4 hours", "4 hours"),
                    ("1-3 days", "1-3 days"),
                    ("4 days to a week", "4 days to a week"),
                    ("1 week to a month", "1 week to a month"),
                    ("1-6 months", "1-6 months"),
                    ("6 months to a year", "6 months to a year"),
                    ("more than year", "more than year"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="datetimeslot",
            name="time_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("8:00", "8:00"),
                    ("9:00", "9:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="symptom_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4 hours", "4 hours"),
                    ("1-3 days", "1-3 days"),
                    ("4 days to a week", "4 days to a week"),
                    ("1 week to a month", "1 week to a month"),
                    ("1-6 months", "1-6 months"),
                    ("6 months to a year", "6 months to a year"),
                    ("more than year", "more than year"),
                ],
                max_length=30,
            ),
        ),
    ]
