# Generated by Django 4.2.1 on 2023-07-12 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0016_weekday_shift_appointmenttimeslot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointmenttimeslot",
            old_name="time_schedule",
            new_name="schedule_time",
        ),
    ]
