# Generated by Django 4.2.1 on 2023-07-14 10:09

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0008_remove_affiliation_name_affiliation_hospital_name"),
        (
            "appointmentio",
            "0017_rename_time_schedule_appointmenttimeslot_schedule_time",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmenttimeslot",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointmenttimeslot",
            name="is_booked",
        ),
        migrations.AlterField(
            model_name="appointmenttimeslot",
            name="weekday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointmentio.weekday"
            ),
        ),
        migrations.CreateModel(
            name="AppointmentDateTimeSlotConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("is_booked", models.BooleanField(default=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointmentio.appointment",
                    ),
                ),
                (
                    "appointment_time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentio.appointmenttimeslot",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountio.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
