# Generated by Django 4.2.1 on 2023-07-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentio", "0018_remove_appointmenttimeslot_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentdatetimeslotconnector",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointmentio.appointment",
            ),
        ),
    ]
