# Generated by Django 4.2.1 on 2023-05-23 11:51

from django.db import migrations, models
import mediaroomio.paths
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mediaroomio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmediaimage",
            name="image",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mediaimage",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                height_field="height",
                upload_to=mediaroomio.paths.get_mediaimage_image_path,
                width_field="width",
            ),
        ),
    ]
