# Generated by Django 4.2.1 on 2023-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaroomio", "0003_historicalmediaimage_item_type_mediaimage_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmediaimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmediaimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
