# Generated by Django 4.2.1 on 2023-05-29 12:30

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0005_remove_affiliation_doctor"),
        ("doctorio", "0002_alter_shift_options_alter_weekday_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="degree",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="expertise",
        ),
        migrations.RemoveField(
            model_name="expertise",
            name="department",
        ),
        migrations.RemoveField(
            model_name="historicaldoctor",
            name="expertise",
        ),
        migrations.AddField(
            model_name="degree",
            name="result",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="DoctorAdditionalConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctorio.achievement",
                    ),
                ),
                (
                    "affiliation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountio.affiliation",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctorio.degree",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctorio.doctor",
                    ),
                ),
                (
                    "expertise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctorio.expertise",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("doctor", "expertise"),
                    ("doctor", "affiliation"),
                    ("doctor", "degree"),
                    ("doctor", "achievement"),
                },
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
