# Generated by Django 4.2.1 on 2023-06-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountio", "0008_remove_affiliation_name_affiliation_hospital_name"),
        ("doctorio", "0004_expertise_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ManyToManyField(to="accountio.organization"),
        ),
    ]
