# Generated by Django 4.2.1 on 2023-06-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctorio", "0005_department_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="appointment_duration",
            field=models.DateTimeField(
                blank=True, help_text="Duration per Appointment", null=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="appointment_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="doctor",
            name="appointment_interval",
            field=models.DateTimeField(
                blank=True, help_text="Interval between Appointment", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldoctor",
            name="appointment_duration",
            field=models.DateTimeField(
                blank=True, help_text="Duration per Appointment", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldoctor",
            name="appointment_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicaldoctor",
            name="appointment_interval",
            field=models.DateTimeField(
                blank=True, help_text="Interval between Appointment", null=True
            ),
        ),
    ]
