# Generated by Django 4.2.1 on 2023-06-14 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "doctorio",
            "0006_doctor_appointment_duration_doctor_appointment_fee_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weekday",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="weekday",
            name="shift",
        ),
        migrations.DeleteModel(
            name="Shift",
        ),
        migrations.DeleteModel(
            name="Weekday",
        ),
    ]
