# Generated by Django 4.2.1 on 2023-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctorio", "0008_alter_doctor_appointment_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="appointment_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="check_up_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="follow_up_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="appointment_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="check_up_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="consultation_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldoctor",
            name="follow_up_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
