# Generated by Django 4.2.1 on 2023-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_SET", "Not Set"),
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "Ab Positive"),
                    ("AB-", "Ab Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                ],
                default="NOT_SET",
                max_length=10,
            ),
        ),
    ]
