# Generated by Django 4.2.1 on 2023-05-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimaryDiseases',
            new_name='PrimaryDisease',
        ),
    ]
